### ISSUE TITLE
Crash in 1.16.2 with Fabric API 0.19.0 and Fabric Loader 0.9.2

### ISSUE THREAD

**Issue by chexo3** [BackportProjectMC/PerspectiveModRedux#2]
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 8/30/20 4:48 PM
Description: Unexpected error

java.lang.NoSuchFieldError: field_1850
	at pm.c7.perspective.PerspectiveMod.lambda$onInitializeClient$0(PerspectiveMod.java:72)
	at net.fabricmc.fabric.api.event.client.ClientTickCallback.lambda$null$0(ClientTickCallback.java:39)
	at net.fabricmc.fabric.impl.event.lifecycle.client.LegacyClientEventInvokers.lambda$onInitializeClient$0(LegacyClientEventInvokers.java:29)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$null$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zjd000$onEndTick(class_310.java:6326)
	at net.minecraft.class_310.method_1574(class_310.java:1577)
	at net.minecraft.class_310.method_1523(class_310.java:996)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pm.c7.perspective.PerspectiveMod.lambda$onInitializeClient$0(PerspectiveMod.java:72)
	at net.fabricmc.fabric.api.event.client.ClientTickCallback.lambda$null$0(ClientTickCallback.java:39)
	at net.fabricmc.fabric.impl.event.lifecycle.client.LegacyClientEventInvokers.lambda$onInitializeClient$0(LegacyClientEventInvokers.java:29)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$null$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zjd000$onEndTick(class_310.java:6326)

-- Affected level --
Details:
	All players: 1 total; [class_746['Dvallin'/692858, l='ClientLevel', x=31.41, y=424.91, z=-35.21]]
	Chunk stats: Client Chunk Cache: 961, 683
	Level dimension: minecraft:the_end
	Level spawn location: World: (0,60,0), Chunk: (at 0,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 136877 game time, 50703373 day time
	Server brand: Waterfall <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:679)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1285203600 bytes (1225 MB) / 2420113408 bytes (2308 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.1
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		durabilityviewer: Giselbaers Durability Viewer 1.16.2-fabric0.17.2-1.8.5
		dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
		fabric: Fabric API 0.19.0+build.398-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.0+516ece7c4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		fiber: fiber 0.23.0-2
		flighthelper: FlightHelper 1.16.2-fabric0.17.2-1.2.1
		gbfabrictools: GBfabrictools 1.2.2+1.16.2
		horsestatsvanilla: Horse Stats Vanilla 4.0.0
		itemscroller: Item Scroller 0.15.0-dev.20200824.205318
		kirin: Kirin UI 1.7-1.16.2
		lambdynlights: LambDynamicLights 1.3.0+1.16.2
		litematica: Litematica 0.0.0-dev.20200824.031346
		lithium: Lithium 0.5.2
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		mambience: MAmbience 2.1.0+1.16.2
		minecraft: Minecraft 1.16.2
		minihud: MiniHUD 0.19.0-dev.20200829.031650
		modmenu: Mod Menu 1.14.6+build.31
		modupdater: ModUpdater 1.1.11+1.16.2-rc2
		nomoreglowingpots: No More Glowing Pots 1.0.2
		okzoomer: Ok Zoomer 4.0.0+1.16.2
		perspectivemod: Perspective Mod Redux 0.0.4
		phosphor: Phosphor 0.6.0+build.7
		presencefootsteps: Presence Footsteps r28+1.16.2
		randomblockplacement: RandomBlockPlacement 1.16.2-fabric0.17.2-1.1.1
		spruceui: SpruceUI 1.6.2
		voxelmap: VoxelMap 1.10.10
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x AMD Ryzen 3 2200G with Radeon Vega Graphics 
```
Seems like something changed in 1.16.2 that affects this mod and a few others.

**Comment by Cynosphere** [comment]
59df2a0 - https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux/files/3062951
