### ISSUE TITLE
Mod Crashes on 1.16.4

### ISSUE THREAD

**Issue by nisutec** [BackportProjectMC/PerspectiveModRedux#5]
Hello,
I have tried to use your mod “PerspectiveModRedux-0.0.5” with Fabric on the Version 1.16.4 but it crashes on startup. 

Game Log:

```
MultiMC version: 0.6.11-1430

Java is version 1.8.0_271, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Mods:
  [✔️] PerspectiveModRedux-0.0.5
  [✔️] replaymod-1.16.4-2.5.1
  [✔️] Skin_Swapper_1.16.3-2.0.1+
  [✔️] sodium-fabric-mc1.16.3-0.1.0

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms3024m, -Xmx9072m, -Duser.language=en]


Minecraft process ID: 21392


Using onesix launcher.

[14:40:13] [main/INFO]: Loading for game Minecraft 1.16.4
[14:40:14] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: perspectivemod requires {fabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:173) ~[fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:739) ~[fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:210) ~[fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:200) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:128) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170) ~[fabric-loader-0.10.8.jar:?]
	... 13 more
Process exited with code 1.
Clipboard copy at: 28 Dec 2020 14:42:32 +0100

```

**Comment by Cynosphere** [comment]
Missing Fabric API.
